# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

jobs:
- job: 'ParallelTesting'
  strategy:
    parallel: 3
  displayName: Run tests in parallel

  steps:
  - task: VSTest@3
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\bin\**\*test.dll
        **\bin\**\*tests.dll
      searchFolder: '$(System.DefaultWorkingDirectory)'
      runOnlyImpactedTests: true
      runAllTestsAfterXBuilds: '3'
      
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(build.sourcesDirectory)'
      includeRootFolder: false

  - task: PublishBuildArtifacts@1

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: $(Agent.TempDirectory)
  - script: echo Hello, world!